language: python
python:
    - 3.6
    - 3.7
    - 3.8
    - 3.9-dev
    - pypy3
matrix:
    include:
        - name: "3.8-pure"
          python: "3.8"
          env: PURE_PYTHON=1
install:
    - pip install -U coveralls coverage coverage-python-version
    - pip install -U six
    - pip install -U zc.buildout
    - buildout bootstrap
    - buildout
script:
    - coverage run bin/test -v1
after_success:
    - coveralls
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
